name: Build and push Workflow

on:
  workflow_call:
    secrets:
      access_key:
        required: true
      secret_key:
        required: true

jobs:
  build:    
    name: Build Image
    runs-on: ubuntu-latest
    outputs:
      STACK2: ${{ steps.set-output-defaults.outputs.stack }}

    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |
          if [ "${GITHUB_REF#refs/heads/}" == "main" ]; then 
              echo "::set-output name=stack::prod }}" 
          fi   
      - name: set outputs with default values
        id: set-output-defaults2
        run: |
          if [ "${GITHUB_REF#refs/heads/}" == "main" ]; then 
              echo "::set-output name=environment::prod }}" 
          elif [ "${GITHUB_REF#refs/heads/}" == "dev" ]; then 
              echo "::set-output name=environment::dev }}" 
          else [ "${GITHUB_REF#refs/heads/}" == "stage" ]
              echo "::set-output name=environment::stage }}" 
          fi  

 