name: Build and push Workflow

on:
  workflow_call:
    secrets:
      access_key:
        required: true
      secret_key:
        required: true
    outputs:
      stack:
        description: "The stack name"
        value: ${{ jobs.build.outputs.stack }}
        

jobs:
  build:    
    name: Build Image
    runs-on: ubuntu-latest
    outputs:
      stack: ${{ steps.out_stack.outputs.stack }}
    steps:
      - name: Set branch-based environment variables
        uses: iamtheyammer/branch-env-vars@v1.1.3
        with:
          bevOverwrite: true
          STACK: |
            main:prod
            dev:dev
            stage:stage
      - id: out_stack
        run: echo "::set-output name=stack::$STACK"