name: Build and push Workflow

on:
  workflow_call:
    secrets:
      access_key:
        required: true
      secret_key:
        required: true

jobs:
  build:    
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set branch-based environment variables
      uses: iamtheyammer/branch-env-vars@v1.1.3
      with:
        bevOverwrite: true
        AWS_REGION: |
          main:us-east-2
          dev:us-west-2
        CLUSTER: |
          main:eks-prod-boris
          dev:eks-dev-boris

    - name: Deploy
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.repo_name }}
        CLUSTER:  ${{ env.CLUSTER }}
        REGION:  ${{ env.AWS_REGION }}
      run: |
        echo $REGION
        echo $CLUSTER

    - name: Extract branch name
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo ${GITHUB_REF#refs/heads/}    

    - name: Get branch name
      run: echo 'The branch name is' $BRANCH_NAME      