name: Build and push Workflow

on:
  workflow_call:
    inputs:   
      stack:
        required: true
        type: string      
    secrets:
      access_key:
        required: true
      secret_key:
        required: true

jobs:
  build:    
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Deploy
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.repo_name }}
        CLUSTER:  ${{ env.CLUSTER }}
        REGION:  ${{ env.AWS_REGION }}
      run: |
        echo $REGION
        echo $CLUSTER
