name: Build and push Workflow

on:
  workflow_call:
    secrets:
      access_key:
        required: true
      secret_key:
        required: true

jobs:
  build:    
    name: Build Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./chart

    steps:

    - name: Check out code
      uses: actions/checkout@v2

- name: Set branch-based environment variables
  uses: iamtheyammer/branch-env-vars@v1.1.3
  with:
    bevOverwrite: true
    AWS_REGION: |
      main:us-east-2
      dev:us-west-2
    CLUSTER: |
      main:eks-prod-boris
      dev:eks-dev-boris

    - name: Deploy
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.repo_name }}
        CLUSTER:  ${{ env.cluster_name }}
        REGION:  ${{ env.AWS_REGION }}
      run: |
        echo $REGION
        echo $CLUSTER

     