name: Build and push Workflow

on:
  workflow_call:
    inputs:   
      stack:
        required: true
        type: string      
    secrets:
      access_key:
        required: true
      secret_key:
        required: true

jobs:
  build:    
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Deploy
      env:
        STACK: ${{ inputs.aws_region }}
      run: |
        echo $STACK
