name: Main Workflow

on:
  push:
    branches:
      - dev
      - main
      - stage
    paths:
      - './**'
      - '.github/**'

jobs:
  call-workflow-deploy-k8s:
    uses: ./.github/workflows/deploy.yml
    with:
      refs: 'GITHUB_REF#refs/heads/'
      stack: 'test'  
    secrets:
      access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}