name: Main Workflow

on:
  push:
    branches:
      - dev
      - main
      - stage
    paths:
      - './**'
      - '.github/**'

jobs:
  EnvSetup:
    name: Setup Dynamic Environment Variables
    runs-on: ubuntu-latest
    outputs:
      build-and-verify: ${{ steps.set-output-defaults.outputs.environment }}
    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |
          echo "::set-output name=environment::prod }}"
   
  call-workflow-deploy-k8s:
    uses: ./.github/workflows/deploy.yml
    needs: EnvSetup
    with:
      aws_region: ${{ github.ref_name }}
      aws_test: ${{needs.EnvSetup.outputs.build-and-verify}}
    secrets:
      access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}