name: Main Workflow

on:
  push:
    branches:
      - dev
      - main
      - stage
    paths:
      - './**'
      - '.github/**'

jobs:                
  call-workflow-build:
    uses: ./.github/workflows/build-push.yml
    secrets:
      access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  call-workflow-deploy-k8s:
    uses: ./.github/workflows/deploy.yml
    needs: call-workflow-build
    with:
      aws_test: ${{needs.set-output-defaults.outputs.STACK}}
    secrets:
      access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}