name: Main Workflow

on:
  push:
    branches:
      - dev
      - main
      - stage
    paths:
      - './**'
      - '.github/**'

env:
  if: github.ref_name == 'main'
    STACK: prod
  if: github.event.action == 'A'
    STACK: ${{github.ref_name}}
    

jobs:
  call-workflow-deploy-k8s:
    uses: ./.github/workflows/deploy.yml
    with:
      aws_region: ${{ github.ref_name }}
      aws_test: ${{ env.STACK }}
    secrets:
      access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}