name: Main Workflow

on:
  push:
    branches:
      - dev
      - main
      - stage
    paths:
      - './**'
      - '.github/**'

jobs:
  env:    
    steps:
    - name: Set branch-based environment variables
      uses: iamtheyammer/branch-env-vars@v1.1.3
      with:
        bevOverwrite: true
        STACK: |
          main:prod
          dev:dev
          stage:stage  
  call-workflow-deploy-k8s:
    uses: ./.github/workflows/deploy.yml
    needs: env
    with:
      aws_region: ${{ github.ref_name }}
      aws_test: ${{ env.STACK }}
    secrets:
      access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}