name: Main Workflow

on:
  push:
    branches:
      - dev
      - main
      - stage
    paths:
      - './**'
      - '.github/**'

jobs:
  init:    
    name: Build Image
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.setvars.outputs.STACK }}

    steps:
    - name: Set variables
      id: setvars
      run: |
        if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
          echo "::set-output name=STACK::prod"
        fi

        if [[ "${{github.ref}}" == "refs/heads/dev" ]]; then
          echo "::set-output name=STACK::dev"
        fi          
   
  call-workflow-deploy-k8s:
    uses: ./.github/workflows/deploy.yml
    needs: init
    with:
      aws_region: ${{ github.ref_name }}
      aws_test: ${{needs.init.outputs.STACK}}
    secrets:
      access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}