name: Test workflow

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - review_requested
    branches: [dev, main, stage]

jobs:
  call-workflow-jest-tests:
    uses: ./.github/workflows/node-tests.yml